# Generated by Django 2.1.7 on 2019-03-14 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190314_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
