# Generated by Django 2.1.7 on 2019-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
