# Generated by Django 2.1.7 on 2019-03-15 17:45

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='option_color',
            field=models.CharField(default=polls.models.generate_random_color, max_length=32),
        ),
    ]
